import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import Footer from "@/shared/components/footer";
import Header from "@/shared/components/header";
import type { Metadata } from "next";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head />
      <body className={cn("min-h-screen bg-background font-sans", fontSans.variable)}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
